name: "Ewelink Switch"
description: "Ewelink Switch"
version: "2.2.2"
slug: "ewelink_switch"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
options:
  deviceid: ""
  devicekey: ""
  apikey: ""
schema:
  deviceid: str
  devicekey: str
  apikey: str
ports:
  8035/tcp: 8035
map:
  - share:rw
